"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.AVAILABLE_COUNTRIES_ISO_CODE = void 0;
var AVAILABLE_COUNTRIES_ISO_CODE;
(function (AVAILABLE_COUNTRIES_ISO_CODE) {
    AVAILABLE_COUNTRIES_ISO_CODE["DK"] = "DK";
    AVAILABLE_COUNTRIES_ISO_CODE["GB_ENG"] = "GB-ENG";
    AVAILABLE_COUNTRIES_ISO_CODE["NO"] = "NO";
    AVAILABLE_COUNTRIES_ISO_CODE["SE"] = "SE";
    AVAILABLE_COUNTRIES_ISO_CODE["NL"] = "NL";
    AVAILABLE_COUNTRIES_ISO_CODE["DE"] = "DE";
    AVAILABLE_COUNTRIES_ISO_CODE["BE"] = "BE";
})(AVAILABLE_COUNTRIES_ISO_CODE = exports.AVAILABLE_COUNTRIES_ISO_CODE || (exports.AVAILABLE_COUNTRIES_ISO_CODE = {}));
